### ISSUE TITLE
python convert_etherscan_csv.py failed

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#32]
parsing failed, 
see screenshot and [.csv](https://drive.google.com/file/d/1dOK_07Hylfqz8FIJRBHFIX2VaqPnH13M/view?usp=sharing)

 attached
![Bildschirmfoto 2021-01-25 um 17 57 09](https://user-images.githubusercontent.com/42371947/105738219-14b24700-5f37-11eb-87e3-3074e01cceaa.png)

**Comment by Ramarti** [comment]
I think we have hit Etherscan's csv export limits. 
The script fails in the last entry because the data is cut short in the csv, there are more token transfers happening for that tx hash so it's trying to classify with missing info.
For now, remove the last entry in the csv (hash: 0x431af6ed42072a164824e2573b888d7f0db745b45dfe5e349c2f16f4a3e9f0b7) and the script will work. 
Note: we need to work on a better source of info in stage 2
