### ISSUE TITLE
USD price feed

### ISSUE THREAD

**Issue by AngelaKTE** [TokenEngineeringCommunity/BalancerPools_Model#5]
- solution research
- map to phase 1 requirements
- implementation
- documentation

**Comment by AngelaKTE** [comment]
Working session required!
- synthetic data:
a) edge cases (conceptually)
b) ranges (tokens, price ranges from/to)
c) time range (blockno, txno...)

**Comment by VasilySumanov** [comment]
We have two approaches to get USD price feeds:
1. Use any kind of on-chain oracle that records data, and get this data. 
**Pros** - it is Uniswap data and it is the most relevant data source since arbitrageurs using it as the trigger for trades.
**Cons** - oracles have from 30 min to 60 min resolution (as every query requires gas, and make it >twice per hour is really costly). It is obviously not enough for calc arb function - since arbitrage trades occur more often according to Etherscan.

2. Use an analytic data aggregator like Messari.io
**Pros** 5 and 15 min intervals for price data feed
**Cons** it is not Uniswap data, it is averaged data from multiple exchanges, and it is (probably) instant data, not time-weighted (if so, it can lead to some simulation problems if there was any kind of spike).
**Cons2** it Is available only in the Enterprise version of Messari (but there are some solutions).

**Comment by VasilySumanov** [comment]
Moreover, I see that we need to have a special function `token_usd_price` using `token_in ` (token type), and the number of these tokens as arguments.

**Comment by Ramarti** [comment]
- We are using TradingView csv exports as external price sources (every 5 mins from first pool transaction to last)
- The script `data/add_external_price_feeds.py` takes the action json generated by `data/convert_ethersca_csv.py` and said price csv export and combines it into a new action json. The first entry will be pool creation, following by an ordered sequence of events (actions) that can be price changes or pool interactions
- The price changes will be introduced in the simulation by `p_action_decoder`, triggering changes in `token_values` state variables that will be spread to individual columns by post procesing method
